version: "3.8"

services:
  notification_service:
    build:
      context: .
    container_name: notification_service
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    restart: on-failure
